spring:
  application:
    name: property-backend

  datasource:
    url: jdbc:mysql://localhost:3306/property_management?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    default-property-inclusion: non_null

server:
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  security:
    jwt-secret: cMySuperSecureKeyForPropertyManagementAppMustBeAtLeast32CharsLong
    token-expiration-minutes: 5256000

logging:
  level:
    org.springframework: INFO
    com.propertymgmt.property: DEBUG
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
